package seeingvoice.jskj.com.seeingvoice.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import seeingvoice.jskj.com.seeingvoice.database.entity.PureTestResult;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pureTestResultDaoConfig;

    private final PureTestResultDao pureTestResultDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pureTestResultDaoConfig = daoConfigMap.get(PureTestResultDao.class).clone();
        pureTestResultDaoConfig.initIdentityScope(type);

        pureTestResultDao = new PureTestResultDao(pureTestResultDaoConfig, this);

        registerDao(PureTestResult.class, pureTestResultDao);
    }
    
    public void clear() {
        pureTestResultDaoConfig.clearIdentityScope();
    }

    public PureTestResultDao getPureTestResultDao() {
        return pureTestResultDao;
    }

}
